# Generated by Django 5.1 on 2025-10-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manim', '0003_code_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ping', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
